### PR TITLE
Update tapenade 3.16

### PR DESCRIPTION
**Pull request by nwu63**
## Purpose
This time I actually updated the Tapenade-generated source code to 3.16.

## Type of change
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing
Existing tests all pass. I kept a tiny diff in one AD'd file to make sure our CI checks are working as expected.

### CODE REVIEW

**Comment by eirikurj** [comment]
Overall, the changes look fine. I am assuming you will update the yml file later to test with 3.16 later?

**Comment by eirikurj** [comment]
@nwu63 haha I guess you beat me to it. However, why did the tapende test not fail before?

**Comment by nwu63** [comment]
I think when I removed those lines in commit `5409a91`, this prevented tapenade from generating any new files. Therefore, `git` did not catch anything as it was comparing nothing to the existing files.

**Review by anilyil — COMMENTED** [review]
Changes look good. My only minor comment: looks like we had the actual build of tapenade printed in the headers after the version, i.e. `Tapenade 3.10 (r5363)` but the new version just has version and `master`. Is it possible to get a more informative thing printed there instead of master? 

Might be a bit easier to match this run in the future, but I may be completely missing the point as well. Is the version number enough to fully define what state of tapenade we used?

**Comment by nwu63** [comment]
I don't think there's a way to change this because we're just using compiled binaries released by them. However, I think in addition to the version, the date there refer to the day that the binaries are built, so together with the version we should be able to uniquely identify which version of tapenade was used to generate these.

**Review by anilyil — DISMISSED** [review]
Okay, then this is good to go for me.

**Comment by nwu63** [comment]
I'm not sure if this is waiting on anyone. @eirikurj can we merge this in?

**Review by lamkina — DISMISSED** [review]
This looks good to me.

**Review by sseraj — COMMENTED** [review]
Can you clarify what the autoEdit changes do?

**Comment by nwu63** [comment]
> Can you clarify what the autoEdit changes do?

I added a few files so that they are not copied over to the actual `output` directories, meaning they will not be compiled or tracked by git. These files are generated as part of Tapenade (I'm sure there's a way to set it up such that they are not generated, but I didn't try this), but the AD'd code are not needed. The ignore list makes sure they are not copied over.

**Review by sseraj — APPROVED** [review]
That makes sense, thanks

**Pull request merged**
