### PR TITLE
Implemented aExp and bExp options

### LINKED ISSUE #40: Implement the aExp and bExp options
# Description of feature
The `aExp` and `bExp` values are currently hard-coded in most of the Fortran code. We should complete the partial implementation to allow users to set these values in Python.

# Potential solution
This will mainly involve modifying how the interpolation weights are computed in ` kd_tree.F90`. See [here](https://github.com/mdolab/idwarp/blob/master/src/modules/kd_tree.F90#L685) for one example.

### PR DESCRIPTION
**Pull request by sseraj**
## Purpose

Closes #40. Please see the issue for some discussion on the performance penalty compared to hard-coded values for the exponents.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

I plan to add a test with non-default exponents in a subsequent PR where I will add a test for MultiUSMesh.

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

### CODE REVIEW

**Review by joanibal — APPROVED** [review]
Looks good to me. This will be very useful. 
Thank you @sseraj!

**Comment by marcomangano** [comment]
As discussed during the maintenance meeting, a test will be added in an upcoming PR

**Comment by nwu63** [comment]
@eirikurj @SichengHe could you take a look at this some time? It would be really helpful to get this feature merged.

**Comment by joanibal** [comment]
@SichengHe @eirikurj. Just another reminder, as I would also like to get this feature on the main branch ASAP

**Review by awccopp — APPROVED** [review]
Everything here looks good to me.

**Pull request merged**
