### PR TITLE
add tagged v 2.2.1

### PR DESCRIPTION
**Pull request by joanibal**
## Purpose
Ping made some tweaks to the interface for DAFoam he'd like tagged. 

The version in the `__init__` file has to be bumped before we can tag a new version.

### CODE REVIEW

**Comment by joanibal** [comment]
@nwu63 Do you know why the tests failed?
I just changed the version number. Did the Docker image change recently?

The error is 
`ifort: error #10052: could not checkout FLEXlm license`

**Comment by nwu63** [comment]
Oh shoot we renamed the docker images but then did not change Travis. I saw pyHyp fail yesterday but it didn't register. I will push a fix for Travis on this PR and then it should pass.

FFR I always directly commit to master when bumping the version number, and maintainers can do the same assuming they have write permission, that way you don't need a PR.

**Comment by nwu63** [comment]
Interesting, are you able to edit the file in your browser?

**Comment by joanibal** [comment]
I didn't try that, but will next time i need to bump a version number. 

Thanks for the help Neil!

**Pull request merged**
